language: r
sudo: required
cache:
  - packages
  - github_packages
dist: trusty
r:
    - 3.4.1
    - oldrel
    - release
r_packages:
    - devtools
    - covr
    - rcmdcheck
matrix:
     include:
         - os: osx
           fortran: false
before_install:
#  - sudo R CMD javareconf
#  - Rscript -e 'install.packages("rJava", type = "source")'

Rscript -e 'install.packages(c("animalr", "lubridate", "readxl", "reshape2", "RODBC", "rmsutilityr", "sqldf", "stringi", "tm", "XM","devtools", "covr", "rcmdcheck"), build = FALSE);if (!all(c("devtools", "covr", "rcmdcheck") %in% installed.packages())) { q(status = 1, save = "no")}'

script:
  - R -e 'r <- rcmdcheck::rcmdcheck(".", args = c("--no-manual")); devtools::test(); quit(save = "no", status = if (length(c(r$errors, r$warnings)) > 0) { 1 } else { 0 }, runLast = FALSE)'
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  - global:
    - CI=TRUE
    - LINTR_COMMENT_BOT=false
#os:
#  - osx
#  - linux
